# Generated by Django 4.2.7 on 2023-12-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DutyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sdut_id", models.CharField(max_length=20)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("totlal_time", models.IntegerField()),
                ("duty_state", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="DutyList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sdut_id", models.CharField(max_length=20)),
                ("day", models.IntegerField()),
                ("frame", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DutyNow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sdut_id", models.CharField(max_length=20)),
                ("start_time", models.DateTimeField()),
                ("duty_state", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Sduter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sdut_id", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20, null=True)),
                ("college", models.CharField(max_length=20, null=True)),
                ("class_number", models.CharField(max_length=20, null=True)),
                ("identity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Youtholer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sdut_id", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20, null=True)),
                ("department", models.CharField(max_length=20, null=True)),
                ("identity", models.IntegerField()),
            ],
        ),
    ]
