# Generated by Django 4.2.7 on 2023-12-12 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Youthol", "0002_alter_sduter_identity_alter_youtholer_identity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dutyhistory",
            old_name="totlal_time",
            new_name="total_time",
        ),
    ]
