# Generated by Django 4.2.7 on 2023-12-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Youthol", "0003_rename_totlal_time_dutyhistory_total_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sdut_id", models.CharField(db_index=True, max_length=20)),
                ("apply_time", models.DateTimeField(db_index=True)),
                ("leave_date", models.DateTimeField(db_index=True)),
                ("day", models.IntegerField()),
                ("frame", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="sduter",
            name="phone",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="dutyhistory",
            name="sdut_id",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="dutyhistory",
            name="start_time",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="dutylist",
            name="day",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="dutylist",
            name="sdut_id",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="dutynow",
            name="sdut_id",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="sduter",
            name="sdut_id",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="youtholer",
            name="sdut_id",
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
