# Generated by Django 4.2.7 on 2023-12-17 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Youthol", "0004_dutyleave_sduter_phone_alter_dutyhistory_sdut_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sduter",
            old_name="class_number",
            new_name="grade",
        ),
    ]
