# Generated by Django 4.2.7 on 2023-12-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Youthol", "0005_rename_class_number_sduter_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="sduter",
            name="first_login",
            field=models.BooleanField(default=True),
        ),
    ]
