# Generated by Django 4.2.7 on 2023-12-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Youthol", "0006_sduter_first_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="dutyhistory",
            name="extra_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dutyhistory",
            name="duty_state",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="dutyhistory",
            name="start_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="dutyhistory",
            name="total_time",
            field=models.IntegerField(default=0),
        ),
    ]
