# Generated by Django 4.2.7 on 2023-12-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Youthol",
            "0007_dutyhistory_extra_time_alter_dutyhistory_duty_state_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dutyhistory",
            name="duty_times",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
