# Generated by Django 4.2.7 on 2023-12-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Youthol", "0009_sduter_birthday_sduter_qq_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomBorrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.CharField(db_index=True, max_length=20)),
                ("sdut_id", models.CharField(db_index=True, max_length=20)),
                ("apply_time", models.DateTimeField(db_index=True)),
                ("start_time", models.DateTimeField(db_index=True)),
                ("end_time", models.DateTimeField(db_index=True)),
                ("cancel", models.BooleanField(default=False)),
                ("cancel_time", models.DateTimeField(null=True)),
            ],
        ),
    ]
