# Generated by Django 4.2.7 on 2023-12-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Youthol", "0010_roomborrow"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomborrow",
            name="apply_people",
            field=models.CharField(db_index=True, default=" ", max_length=20),
        ),
    ]
