# Generated by Django 4.2.7 on 2024-01-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Youthol", "0011_roomborrow_apply_people"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtholer",
            name="position",
            field=models.CharField(default="成员", max_length=20),
        ),
    ]
